version: "3"

services:
    MQTT:
        container_name: mqtt
        image: eclipse-mosquitto
        volumes:
            - $DOCKER_FOLDER/mosquitto/config:/mosquitto/config
            - $DOCKER_FOLDER/mosquitto/data:/mosquitto/data
            - $DOCKER_FOLDER/mosquitto/log:/mosquitto/log
        ports:
            - "1883:1883"
            - "9001:9001"
        restart: always
        environment:
            - TZ=$TZ