version: "3"

services:
    vscode:
        container_name: vscode
        image: codercom/code-server:latest
        volumes:
            - /opt/docker/containers/vscode:/home/coder/.local/share/code-server
            - /opt/docker/containers/homeassistant:/home/coder/project
        ports:
            - "8443:8443"
        environment:
            - PUID=$PUID
            - PGID=$PGID
            - TZ=$TZ