version: "3"

services:
    vscode:
        container_name: vscode
        image: linuxserver/code-server
        restart: unless-stopped
        volumes:
            - /opt/docker/containers/vscode:/config
            - /opt/docker/containers/homeassistant:/config/workspace
        ports:
            - "8443:8443"
        environment:
            - PUID=$PUID
            - PGID=$PGID
            - TZ=$TZ