version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - $DOCKER_FOLDER/nginx/sites-enabled:/etc/nginx/conf.d
        ports:
            - "80:80"
        restart: always
        environment:
            - TZ=$TZ
