version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - $DOCKER_FOLDER/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=$TZ
    devices:
      # Make sure this matched your adapter location
      - $USB_DEVICE_PATH:/dev/ttyACM0
    group_add:
      - dialout
    user: $PUID:$PGID